/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * statisticsScreen.java
 *
 * Created on Nov 3, 2009, 7:12:47 PM
 */

package checkers;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jmalmskog
 */
public class statisticsScreen extends javax.swing.JPanel {

    /** Creates new form statisticsScreen */
    public statisticsScreen() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 36));
        jLabel1.setText("Statistics");

        jButton1.setText("Get Stats");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("username");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel7.setFont(new java.awt.Font("Ravie", 1, 14));
        jLabel7.setText("Player 1");

        jLabel8.setFont(new java.awt.Font("Ravie", 1, 14));
        jLabel8.setText("Player 2");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(32, 32, 32)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(layout.createSequentialGroup()
                                .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(29, 29, 29)
                                .add(jLabel8)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .add(32, 32, 32))
            .add(layout.createSequentialGroup()
                .add(183, 183, 183)
                .add(jButton1)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8))
                .add(33, 33, 33)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 154, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButton1)
                .add(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double [] statistics = null;
        if (jTextField1.getText() != null)
            playerOne = jTextField2.getText();

        if (jTextField2.getText() != null)
            playerTwo = jTextField1.getText();
        try {
            statistics = getStats();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(statisticsScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(statisticsScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        String stats = "";
        for(int i = 0; i < 5; i++)
        {
            if(i == 0)
                stats = stats + "Games played: ";
            if(i == 1)
                stats = stats + "Games won: ";
            if(i == 2)
                stats = stats + "Games lost: ";
            if(i == 3)
                stats = stats + "Games drawn : ";
            if(i == 4)
            {
                DecimalFormat twoDForm = new DecimalFormat("#.##");
		statistics[i] = Double.valueOf(twoDForm.format(statistics[i]));
                stats = stats + "Win Percentage: ";
            }

            stats = stats + statistics[i] + "\n";
            
        }
        jTextArea1.setText(stats);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    String playerOne = null;
    String playerTwo = null;
    private double[] getStats() throws FileNotFoundException, IOException//returns an array of games played, won, lost, drawn, and win %
    {


        
        playerOne = "users/" + playerOne + ".txt";
        Scanner one = new Scanner(new File(playerOne));
        //BufferedReader one = new BufferedReader(new FileReader(playerOne));
        //User_Saver one = new User_Saver(playerOne);
        //User_Saver two = new User_Saver(playerTwo);
        double stats[] = new double[5];
        double gamesPlayed = 0;
        double gamesWon = 0;
        double winPercentage = 0;
        double gamesLost = 0;
        double gamesDrawn = 0;
        String line = one.nextLine();line = one.nextLine();
        System.out.println(line);
        //System.out.println(playerTwo);
        //System.out.println("After PlayerTwo");
        if(playerTwo.compareTo("username") == 0){
            System.out.println("if");
            while(one.hasNextLine())
            {
                
                System.out.println(line);
                line = one.nextLine();
                line = one.nextLine();
                //System.out.println(line);
                if(line.compareToIgnoreCase("W") == 0)
                    gamesWon+=1;
                if(line.compareToIgnoreCase("L") == 0)
                    gamesLost+=1;
                if(line.compareToIgnoreCase("D") == 0)
                    gamesDrawn+=1;
                gamesPlayed+=1;

            }
        }
        else{
            System.out.println("else");
            while(one.hasNextLine())
            {
                line = one.nextLine();
                if(line != null)
                if(line.compareToIgnoreCase(playerTwo) == 0)

                    {
                        line = one.nextLine();

                        if(line.compareToIgnoreCase("W") == 0)
                            gamesWon+=1;
                        if(line.compareToIgnoreCase("L") == 0)
                            gamesLost+=1;
                        if(line.compareToIgnoreCase("D") == 0)
                            gamesDrawn+=1;
                        gamesPlayed+=1;

                    }
            }
        }
        one.close();
        winPercentage = gamesWon/gamesPlayed;
        stats[0]=gamesPlayed;
        stats[1]=gamesWon;
        stats[2]=gamesLost;
        stats[3]=gamesDrawn;
        stats[4]=winPercentage;

        return stats;

    }

}
