/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * statisticsScreen.java
 *
 * Created on Nov 3, 2009, 7:12:47 PM
 */

package checkers;

/**
 *
 * @author jmalmskog
 */
public class statisticsScreen extends javax.swing.JPanel {

    /** Creates new form statisticsScreen */
    public statisticsScreen() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 36));
        jLabel1.setText("Statistics");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(48, 48, 48)
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .add(32, 32, 32)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 290, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 154, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private String playerOne = (String) jComboBox1.getSelectedItem();
    private String playerTwo = (String) jComboBox2.getSelectedItem();
    User_Saver one = new User_Saver(playerOne);
    User_Saver two = new User_Saver(playerTwo);
    // End of variables declaration//GEN-END:variables

    private double[] getStats()//returns games played, won, lost, drawn, and win %
    {
        double stats[] = new double[5];
        double gamesPlayed = 0;
        double gamesWon = 0;
        double winPercentage = 0;
        double gamesLost = 0;
        double gamesDrawn = 0;

        if(playerTwo == null)
            for(int i = 2; i<one.lines_infile(); i+=2)
            {
                if(one.get_line(i+1).compareToIgnoreCase("W") == 0)
                    gamesWon+=1;
                if(one.get_line(i+1).compareToIgnoreCase("L") == 0)
                    gamesLost+=1;
                if(one.get_line(i+1).compareToIgnoreCase("D") == 0)
                    gamesDrawn+=1;
                gamesPlayed+=1;

            }
        else
            for(int i = 2; i<one.lines_infile(); i+=2)
            {
                if(one.get_line(i).compareToIgnoreCase(playerTwo) == 0)
                {
                    if(one.get_line(i+1).compareToIgnoreCase("W") == 0)
                        gamesWon+=1;
                    if(one.get_line(i+1).compareToIgnoreCase("L") == 0)
                        gamesLost+=1;
                    if(one.get_line(i+1).compareToIgnoreCase("D") == 0)
                        gamesDrawn+=1;
                    gamesPlayed+=1;
                }
            }
        winPercentage = gamesWon/gamesDrawn;
        stats[0]=gamesPlayed;
        stats[1]=gamesWon;
        stats[2]=gamesLost;
        stats[3]=gamesDrawn;
        stats[4]=winPercentage;

        return stats;

    }

}
